Controllers/LessonViewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;//Entity Framwork Logic
using Microsoft.AspNet.Identity;//Access to Identity Framework Classes and GetUserId()

namespace FamilySite.UI.MVC.Controllers
{
    [Authorize]
    public class LessonViewsController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: LessonViews
       
        public ActionResult Index()
        {
            if (User.IsInRole("Admin") || User.IsInRole("Parent"))
            {

                return RedirectToAction("IndexManager");

            }
            else
            {
                //displays the current user's lessons viewed.
                //1)Get the current user's ID
                //2)use the ID to filter the results from ALL items in the lesson views table.

                //1)
                string currentUserID = User.Identity.GetUserId();

                //2)

                var lessonViews = db.LessonViews.Include(l => l.Lesson).Include(l => l.UserDetail).Where(x => x.UserID == currentUserID);
                return View(lessonViews.ToList());
            }
            
        }

        [Authorize(Roles ="Admin, Parent")]
        public ActionResult IndexManager(string filter)
        {
            
            var lessonViews = db.LessonViews.Include(l => l.Lesson).Include(l => l.UserDetail);

            var members = db.UserDetails.ToList();

            foreach (var x in members)
            {
                if (!string.IsNullOrEmpty(filter))
                {
                    if(x.UserID == filter)
                    {
                        lessonViews =
                            db.LessonViews.Where(l => l.UserDetail.FirstName == x.FirstName).Include(l => l.Lesson).Include(l => l.UserDetail);
                    }
                }
            }

            ViewBag.filter = new SelectList(db.UserDetails, "UserID", "FirstName");        

            return View(lessonViews.ToList());
        }


        

        // GET: LessonViews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string currentUserID = User.Identity.GetUserId();
            LessonView lessonView = db.LessonViews.Find(id);
            if (lessonView == null)
            {
                return HttpNotFound();
            }
             else
            {
                if (User.IsInRole("Parent") || User.IsInRole("Admin") || lessonView.UserID == currentUserID)
                {
                    return View(lessonView);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
        }

        [Authorize(Roles ="Admin")]
        // GET: LessonViews/Create
        public ActionResult Create()
        {
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle");
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: LessonViews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonViewID,UserID,LessonID,DateViewed")] LessonView lessonView)
        {
            if (ModelState.IsValid)
            {
                db.LessonViews.Add(lessonView);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle", lessonView.LessonID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", lessonView.UserID);
            return View(lessonView);
        }

        [Authorize(Roles = "Admin")]
        // GET: LessonViews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LessonView lessonView = db.LessonViews.Find(id);
            if (lessonView == null)
            {
                return HttpNotFound();
            }
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle", lessonView.LessonID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", lessonView.UserID);
            return View(lessonView);
        }

        [Authorize(Roles = "Admin")]
        // POST: LessonViews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LessonViewID,UserID,LessonID,DateViewed")] LessonView lessonView)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lessonView).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle", lessonView.LessonID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", lessonView.UserID);
            return View(lessonView);
        }

        [Authorize(Roles = "Admin")]
        // GET: LessonViews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LessonView lessonView = db.LessonViews.Find(id);
            if (lessonView == null)
            {
                return HttpNotFound();
            }
            return View(lessonView);
        }

        [Authorize(Roles = "Admin")]
        // POST: LessonViews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LessonView lessonView = db.LessonViews.Find(id);
            db.LessonViews.Remove(lessonView);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;
using Microsoft.AspNet.Identity;//User.Identity.GetUserId()
using System.Drawing;
using FamiliySite.Domain.Services;
//using System.Drawing;

namespace FamilySite.UI.MVC.Controllers
{
    [Authorize]
    public class UserDetailsController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: UserDetails
        public ActionResult Index()
        {
            var userDetails = db.UserDetails.Include(u => u.AspNetUser);

            string currentUserID = User.Identity.GetUserId();

            if (currentUserID == null)
            {
                ViewBag.anonymousUser = "Please Resister or Log in to see members info.";
                return View();
            }

            ViewBag.currentUser = currentUserID;
            return View(userDetails.ToList());
        }


        // GET: UserDetails/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
                return View(userDetail);
        }

        // GET: UserDetails/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            string currentUserID = User.Identity.GetUserId();

            ViewBag.UserID = new SelectList(db.AspNetUsers.Where(a => a.Id == currentUserID), "Id", "Email");


            if (User.IsInRole("Admin"))
            {
                ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            }
                      
            return View();
        }

        // POST: UserDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [Authorize(Roles ="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,FirstName,LastName,AvatarImage")] UserDetail userDetail)
        {
            if (db.UserDetails.Where(u => u.UserID == userDetail.UserID).Count() > 0)
            {
                ViewBag.alreadyExists = true;
                ViewBag.UserID = userDetail.UserID;
                return View();
            }
            
            if (ModelState.IsValid)
            {
                
                db.UserDetails.Add(userDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", userDetail.UserID);
            return View(userDetail);
        }

        // GET: UserDetails/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }

            string currentUserID = User.Identity.GetUserId();
            if (User.IsInRole("Admin") || userDetail.UserID == currentUserID)
            {
                //ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", userDetail.UserID);
                return View(userDetail);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }//end else

        }

        // POST: UserDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,FirstName,LastName,AvatarImage")] UserDetail userDetail, HttpPostedFileBase avatarImage)
        {
            if (ModelState.IsValid)
            {
                #region Simple File Upload
                //set a default image name (noImage.jpg)
            
                //if the input has a file (is not null)
                if (avatarImage != null)
                {
                    //store the new file name
                    string image = avatarImage.FileName;

                    //extract the extension and save it in a variable
                    string ext = image.Substring(image.LastIndexOf("."));//.jpg, .gif, etc.
                    //create a whitelist of valid extensions
                    string[] goodExts = new string[] { ".jpg", ".jpeg", ".gif", ".png" };

                    //check our extension vs the whitelist
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        //if we have a good ext, creat a new Unique file name and add the extension
                        //Global Unique Identifier
                        image = Guid.NewGuid() + ext;
                        //save the new file to the webserver
                        //avatarImage.SaveAs(Server.MapPath("~/Content/Images/Users/" + image));

                        #region to generate full & thumnail images //! using FamilySite.Domain.Services
                        string savePath = Server.MapPath("~/Content/Images/Users/");

                        Image convertedImage = Image.FromStream(avatarImage.InputStream);
                        ImageUtilities.ResizeImage(savePath, image, convertedImage, 500, 100);
                        userDetail.AvatarImage = image;
                        #endregion

                        if (Session["currentImage"].ToString() != "noImage.jpg")
                        {
                            System.IO.File.Delete(Server.MapPath("~/Content/Images/Users/" + Session["currentImage"].ToString()));
                            System.IO.File.Delete(Server.MapPath("~/Content/Images/Users/t_" + Session["currentImage"].ToString()));
                        }
                    }
                         
                }

                //no matter what - add the image value back to the record.
                //save to DB //associating the uploaded file (name) to the model record being added
                #endregion

                db.Entry(userDetail).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            //ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", userDetail.UserID);
            return View(userDetail);
        }

        // GET: UserDetails/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            //Handle any delete that would orphon an connected record but this delete function deletes only the profile image.
            //if (userDetail.Reservations.Count > 0 || userDetail.LessonViews.Count >0)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            
            return View(userDetail);
        }

        // POST: UserDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserDetail userDetail = db.UserDetails.Find(id);
           
            
            if (userDetail.AvatarImage != "noImage.jpg")
            {
                System.IO.File.Delete(Server.MapPath("~/Content/Images/Users/" + userDetail.AvatarImage));

                //if you had a thumbnail, you would want to delete it as well.
                System.IO.File.Delete(Server.MapPath("~/Content/Images/Users/t_" + userDetail.AvatarImage));
            }
            userDetail.AvatarImage = "noImage.jpg";


            db.Entry(userDetail).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HyungJin Kang's Family Learning Site'" />
    <meta name="keywords" content="Hyungjin Kang, Hyosoon Lee, family, education, learn" />
    <meta name="author" content="hyungjin kang" />


    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <link href="https://fonts.googleapis.com/css?family=Oxygen:300,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Vibur&display=swap" rel="stylesheet">
    <!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <!-- Bootstrap  -->
    @*<link rel="stylesheet" href="~/Content/css/bootstrap.css">*@
    @Styles.Render("~/Content/css")

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/Content/css/flexslider.css">

    <link rel="stylesheet" href="~/Content/css/style.css">
    @Scripts.Render("~/bundles/modernizr")
    <!-- Modernizr JS -->
    @*<script src="~/Content/js/modernizr-2.6.2.min.js"></script>*@
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <!-- Theme style  -->
    <!--JqueryUI Stylesheet-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />

    <!--Datatables.net Stylesheet-->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

    <!--Custom Stylesheet to override all other styles and create our own-->
    <link href="~/Content/css/CustomStyles.css" rel="stylesheet" />
    <style type="text/css">
        .responsive {
            width: 100%;
            height: 0;
            padding-bottom: 56.25%;
            position: relative;
        }
        .responsive iframe {
            position: absolute;
            width: 100%;
            height: 100%;
        }
    </style>


</head>
<body id="main">

    <div class="fh5co-loader"></div>

    <div id="page">
        <header id="header">
            <nav class="fh5co-nav" role="navigation">
                <div class="container-wrap">
                    <div class="top-menu" style="background-image:url(../../Content/images/wood.jpg)">
                        <div class="row">

                            <div class="col-xs-2">
                                <div id="fh5co-logo"><a href="@Url.Action("Index", "Home")">Family</a></div>
                            </div>
                            <div class="col-xs-8 text-left menu-1">
                                    <ul>
                                        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                                        <li class="has-dropdown">
                                            @Html.ActionLink("Courses", "Index", "Courses")
                                            @if (User.Identity.IsAuthenticated)
                                                {
                                                <ul class="dropdown">
                                                    <li>@Html.ActionLink("Course Completion", "Index", "CourseCompletions")</li>
                                                </ul>
                                                }

                                        </li><!--course-->
                                        <li class="has-dropdown">
                                            @Html.ActionLink("Lessons", "Index", "Lessons")
                                            @if (User.Identity.IsAuthenticated)
                                                {
                                                <ul class="dropdown">
                                                    <li>@Html.ActionLink("Lesson Views", "Index", "LessonViews")</li>
                                           
                                                        <li>@Html.ActionLink("Reservation", "Index", "Reservations")</li>
                                                  
                                                </ul>
                                                }
                                        </li><!--lesson-->

                                        <li>@Html.ActionLink("Member", "Index", "UserDetails")</li>
                                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                    </ul>
                            </div>
                            <div class="col-xs-push-4 text-right menu-1">
                                @Html.Partial("_LoginPartial")
                            </div>  <!--admin menu-->
                        </div>

                        <div class="row">
                            <div class="col-xs-pull-5 text-right menu-1">
                                <ul>
                                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                    }

                                </ul>                       
                            </div>
                        </div>
                    </div>
               </div>
            

            </nav> <!-- END Navigation -->
        </header>

        <div class="container-wrap">

            @RenderBody()

        </div>
        <div class="container-wrap">
            <footer id="footer">
                <div class="col-md-12 text-center">
                    
                    <div>Copyright &copy; @DateTime.Now.Year - HJKANG, All rights reserved</div>
                    
                    <div>
                        This app has been live since
                        @System.Web.HttpContext.Current.Application["launchTimestamp"]
                    </div>
                </div>
            </footer>
        </div><!-- END container-wrap -->
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>



    <!-- jQuery -->
    <script src="~/Content/js/jquery.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")*@

    <!-- jQuery Easing -->
    <script src="~/Content/js/jquery.easing.1.3.js"></script>

    <!-- Bootstrap -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    @*@Scripts.Render("~/bundles/bootstrap")*@

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Waypoints -->
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <!-- Flexslider -->
    <script src="~/Content/js/jquery.flexslider-min.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/magnific-popup-options.js"></script>
    <!-- Counters -->
    <script src="~/Content/js/jquery.countTo.js"></script>
    <!-- Main -->
    <script src="~/Content/js/main.js"></script>

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    @RenderSection("Scripts", required: false)


    <script>
        $(document).ready(function () {
            $('.table').DataTable();
        });
    </script>

</body>
</html>



Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                    <li>@Html.ActionLink("Course Completion", "Index", "CourseCompletions")</li>
                    <li>@Html.ActionLink("Lessons", "Index", "Lessons")</li>
                    <li>@Html.ActionLink("Lesson Views", "Index", "LessonViews")</li>
                    <li>@Html.ActionLink("Reservation", "Index", "Reservations")</li>


                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>