Models/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;


namespace FamilySite.UI.MVC.Models
{
    public class ContactViewModel
    {
        //fields

        //properties
        [StringLength(100, ErrorMessage = "Less than 100 characters")]
        [Required(ErrorMessage = "* Required")]
        public string Name { get; set; }

        [Required(ErrorMessage ="* Required")]
        [EmailAddress(ErrorMessage = "* Please enter valid email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "* Required")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "* Required")]
        public string Message { get; set; }
        //Get: ContactView
    }
}

Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;

namespace FamilySite.UI.MVC.Controllers
{
    public class CoursesController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: Courses
        public ActionResult Index()
        {
            return View(db.Courses1.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }


            var lessons = db.Lessons.Include(l => l.Cours).Where(l => l.CourseID == course.CourseID);
            ViewBag.courseLessons = lessons.ToList();

            return View(course);

        }

        [Authorize(Roles = "Admin")]
        // GET: Courses/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,CourseName,Description,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses1.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,CourseName,Description,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses1.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses1.Find(id);
            db.Courses1.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;
using Microsoft.AspNet.Identity;//User.Identity.GetUserId()
using System.Net.Mail;

namespace FamilySite.UI.MVC.Controllers
{
    public class LessonsController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: Lessons
        public ActionResult Index()
        {
            var lessons = db.Lessons.Include(l => l.Cours);
            return View(lessons.ToList());
        }

        // GET: Lessons/Details/5
        public ActionResult Details(int? id)//id = lesson id
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }

            #region lesson view record creation (coder: hjkang)
            string currentUserID = User.Identity.GetUserId();
            if (currentUserID != null)
            {
                //LessonView lessonview = new LessonView() {LessonID=lesson.LessonID, UserID=currentUserID, DateViewed=DateTime.Now };

                //lessonview.LessonID = lesson.LessonID;
                //lessonview.UserID = currentUserID;
                //lessonview.DateViewed = DateTime.Now;
                db.LessonViews.Add(new LessonView() { LessonID = lesson.LessonID, UserID = currentUserID, DateViewed = DateTime.Now });
                db.SaveChanges();

                #endregion

                #region record creation of course completion  (coder: hjkang)
                // if # of lessons in the course == # of lesson views by the user, then the course of the user is completed.

                //# of lessons in the course

                //# of lesson views for the course 
                var nbrLessonsViewed = 0;
                //var lessonViews = db.LessonViews.
                 //                 Where(x => (x.Lesson.CourseID == lesson.CourseID)
                 //                       && (x.UserID == currentUserID));
                var fc = db.LessonViews.Where(x => (x.Lesson.CourseID == lesson.CourseID)
                                        && (x.UserID == currentUserID)).OrderBy(x => x.LessonID).ToList();

                if (fc.Count() == 1)
                {
                    nbrLessonsViewed = 1;
                }
                else
                {
                    for (int i = 0; i < (fc.Count() - 1); i++)
                    {
                        var elementA = fc.ElementAt(i);
                        var elementB = fc.ElementAt(i + 1);
                        if (elementA.LessonID != elementB.LessonID)
                        {
                            nbrLessonsViewed++;
                        }
                    }
                    nbrLessonsViewed += 1;
                }
                //var nbrLessons = db.Lessons.Where(x => x.CourseID == lesson.CourseID).Count();

                if (nbrLessonsViewed == db.Lessons.Where(x => x.CourseID == lesson.CourseID).Count())
                {
                    //courseComplete.UserID = currentUserID;
                    //courseComplete.CourseID = lesson.CourseID;
                    //courseComplete.DateCompleted = DateTime.Now;

                    //CourseCompletion courseComplete = new CourseCompletion() { UserID = currentUserID, CourseID = lesson.CourseID, DateCompleted = DateTime.Now };

                    db.CourseCompletions.Add(new CourseCompletion() { UserID = currentUserID, CourseID = lesson.CourseID, DateCompleted = DateTime.Now });
                    db.SaveChanges();

                    //send email to the parent(a manager) to notify when a child completes a course
                    //var user = db.UserDetails.Where(u => u.UserID == currentUserID).SingleOrDefault();

                    string body = string.Format($"{db.UserDetails.Where(u => u.UserID == currentUserID).SingleOrDefault().FirstName}"
                        + " has completed " + $"the course of {lesson.Cours.CourseName}" + $" on {DateTime.Now}.");

                    MailMessage msg = new MailMessage(
                        "no-reply@hjkangweb.com",
                        "speedkhj@gmail.com",
                        "Your child completed a course.",
                        body);

                    msg.IsBodyHtml = true;
                    msg.CC.Add("postmaster@hjkangweb.com");

                    SmtpClient client = new SmtpClient("mail.hjkangweb.com");

                    client.Credentials = new NetworkCredential("no-reply@hjkangweb.com", "kang1226@@");
                    client.EnableSsl = false;
                    client.Port = 25;

                    using (client)
                    {
                        try
                        {
                            client.Send(msg);
                        }
                        catch
                        {
                            ViewBag.ErrorMessage = "There was an error sending complete notification. \n" + "Please notify your parent you have completed the course.";
                        }
                    }

                }

                #endregion
            }

            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonID,LessonTitle,CourseID,Introduction,VideoURL,PdfFileName,IsActive,ReservationLimit")] Lesson lesson, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
                string lessonMaterial = "noFile.jpg";
                if (pdfFile != null)
                {
                    lessonMaterial = pdfFile.FileName;
                    string ext = lessonMaterial.Substring(lessonMaterial.LastIndexOf("."));
                    //.pdf, .doc, .docx, .html, .xlsx, .jpg
                    string[] goodExts = new string[] { ".pdf", ".doc", ".docx", ".html", ".xlsx", ".xls", ".jpg", ".png", ".gif", ".jpeg" };
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        lessonMaterial = Guid.NewGuid() + lessonMaterial;
                        pdfFile.SaveAs(Server.MapPath("~/Content/textfiles/Lessons/" + lessonMaterial));
                    }
                    else
                    {
                        lessonMaterial = "noFile.jpg";
                    }
                }
                lesson.PdfFileName = lessonMaterial;

                db.Lessons.Add(lesson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LessonID,LessonTitle,CourseID,Introduction,VideoURL,PdfFileName,IsActive,ReservationLimit")] Lesson lesson, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
               
                if (pdfFile != null)
                {
                    string lessonMaterial = pdfFile.FileName;
                    string ext = lessonMaterial.Substring(lessonMaterial.LastIndexOf("."));
                    //.pdf, .doc, .docx, .html, .xlsx, .jpg
                    string[] goodExts = new string[] { ".pdf", ".doc", ".docx", ".html", ".xlsx", ".xls", ".jpg", ".png", ".gif", ".jpeg" };
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        lessonMaterial = Guid.NewGuid() + lessonMaterial;
                        pdfFile.SaveAs(Server.MapPath("~/Content/textfiles/Lessons/" + lessonMaterial));
                        lesson.PdfFileName = lessonMaterial;

                        if(Session["currentFile"].ToString() != "noFile.jpg") 
                        {
                            System.IO.File.Delete(Server.MapPath("~/Content/textfiles/Lessons/" + Session["currentFile"].ToString()));
                        }
                    }                   
                }

                db.Entry(lesson).State = EntityState.Modified;
                db.SaveChanges();

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div id="family-wrapper">
    <hgroup>
        <h2>@ViewBag.Title.</h2>
        <h3>@ViewBag.Message</h3>
    </hgroup>
    <div class="row-fluid">
        <div class="span12">
            <p>This is my family's learning web site.</p>
        </div>
    </div>
</div>

Views/Home/Contact.cshtml

@model FamilySite.UI.MVC.Models.ContactViewModel
@{
    ViewBag.Title = "Get In Touch";
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>
    <div class="status alert alert-success" style="display: none"></div>
    <div id="contact">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div id="CourseDetailsContainer">
                <div class="form-group col-md-12" style="margin-top:1em;">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Name" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-12">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-12">
                    @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @placeholder = "Subject" })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-md-12" style="width:100%">
                    @Html.TextAreaFor(model => model.Message, new { @class = "form-control", @placeholder = "Message", @id = "message", @row = 8 })
                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                </div>
                <div class="clearfix"></div>
                <div id="tdFooterRight">

                    <input type="submit"
                           value="Send Message"
                           name="submit"
                           class="btn btn-primary pull-right" />
                </div>
                <div class="clearfix"></div>

            </div>

        }
    </div>
</div>

@section scripts {
    <script src="~/Content/js/formvalidation.js"></script>
}

Views/Home/ContactConfirmation.cshtml
@model FamilySite.UI.MVC.Models.ContactViewModel

@{
    ViewBag.Title = "Contact Confirmation";
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>
    <hr />

    <div id="CourseDetailsContainer">
        <!--Response Message (if the message was sent to us successfully)-->
        <h4>
            Thank you for contacting us, @Model.Name!!! We will get back to you within 24 hours.
        </h4>  
    </div>
          
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

@model FamilySite.DATA.EF.Lesson

<div class="container-wrap">
    <aside id="fh5co-hero">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url(../../Content/images/img_bg_1_1.jpg);">
                    <div class="overlay-gradient"></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 col-md-pull-3 slider-text">
                                <div class="slider-text-inner">
                                    <h1 style="font-weight:700">Family Learnig Site</h1>
                              
                                    <p><a class="btn btn-primary btn-demo" href=@Url.Action("Index","Courses")>Courses</a> <a class="btn btn-primary btn-learn" href=@Url.Action("Index","Lessons")>Lessons</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(../../Content/images/img_bg_2_1.jpg);">
                    <div class="overlay-gradient"></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 col-md-push-3 slider-text">
                                <div class="slider-text-inner">
                                    <h1>My Page </h1>
                             
                                    <p><a class="btn btn-primary btn-demo" href=@Url.Action("Index","CourseCompletions")>My Completed Courses</a> <a class="btn btn-primary btn-learn" href=@Url.Action("Index","Reservations")>Reservations</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(../../Content/images/img_bg_3_1.jpg);">
                    <div class="overlay-gradient"></div>
                    <div class="container-fluids">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 slider-text">
                                <div class="slider-text-inner text-center">
                                    <h1>Members</h1>

                                    <p><a class="btn btn-primary btn-demo" href=@Url.Action("Index","UserDetails")>Members</a> <a class="btn btn-primary btn-learn" href=@Url.Action("Contact","Home")>Contact</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(../../Content/images/img_bg_4_1.jpg);">
                    <div class="overlay-gradient"></div>
                    <div class="container-fluid">
                        @*<div class="row">
                            <div class="col-md-6 col-md-offset-3 col-md-push-3 slider-text">
                                <div class="slider-text-inner">
                                    <h1>I Love to Tell My Story</h1>
                                    <h2>Free html5 templates Made by <a href="http://freehtml5.co/" target="_blank">freehtml5.co</a></h2>
                                    <p><a class="btn btn-primary btn-demo" href="#"></i> View Demo</a> <a class="btn btn-primary btn-learn">Learn More</a></p>
                                </div>
                            </div>
                        </div>*@
                    </div>
                </li>
            </ul>
        </div>
    </aside>

    <div id="fh5co-work" class="fh5co-light-grey">
        <div class="row animate-box">
            <div class="col-md-6 col-md-offset-3 text-center fh5co-heading">
                <h2 style="font-size:1.7em;">Popular Lessons</h2>
                <p style="font-size: 1.5em; font-weight:400;">Here are fun and great lessons for family members!</p>
            </div>
        </div>

      
        <div class="row">
            <div class="col-md-4 text-center animate-box">
                <a href="@Url.Action("Details", "Lessons", new { @id = ViewBag.lessonNo1 })" class="work" style="background-image: url(../../Content/images/Lessons/diamond.jpg);"> <!-- 3-->
                    <div class="desc">
                        <h3>Most Popular</h3>
                        <span>Amazing</span>
                    </div>
                </a>

            </div>
            <div class="col-md-4 text-center animate-box">
                <a href="@Url.Action("Details", "Lessons", new { @id = ViewBag.lessonNo2 })" class="work" style="background-image: url(../../Content/images/Lessons/gold.jpg);"> <!-- 15-->
                    <div class="desc">
                        <h3>2nd Popular</h3>
                        <span>Very Good</span>
                    </div>
                </a>
            </div>
            <div class="col-md-4 text-center animate-box">
                <a href="@Url.Action("Details", "Lessons", new { @id = ViewBag.lessonNo3 })" class="work" style="background-image: url(../../Content/images/Lessons/flowers.jpg);"> <!-- 12 -->
                    <div class="desc">
                        <h3>3rd Popular</h3>
                        <span>Enjoyable</span>
                    </div>
                </a>
            </div>
        </div>

        
    </div>

    <div id="fh5co-counter" class="fh5co-counters">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center animate-box">
                <p style="font-size: 1.5em; font-weight:400;">Here are number of Courses, Lessons, Courses completed, Lesson Viewed!</p>
            </div>
        </div>
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2">
                <div class="row">
                    <div class="col-md-3 text-center">
                        <span class="glyphicon glyphicon-file"></span>
                        <span class="fh5co-counter js-counter" data-from="0" data-to="@ViewBag.coursesNo" data-speed="1000" data-refresh-interval="50"></span>
                        <span class="fh5co-counter-label">COURSES</span>
                    </div>
                    <div class="col-md-3 text-center">
                        <span class="glyphicon glyphicon-floppy-disk"></span>
                        <span class="fh5co-counter js-counter" data-from="0" data-to="@ViewBag.lessonsNo" data-speed="1000" data-refresh-interval="50"></span>
                        <span class="fh5co-counter-label">LESSONS</span>
                    </div>
                    <div class="col-md-3 text-center">
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="fh5co-counter js-counter" data-from="0" data-to="@ViewBag.courseCompletionsNo" data-speed="1000" data-refresh-interval="50"></span>
                        <span class="fh5co-counter-label">COURSE COMPLETIONS</span>
                    </div>
                    <div class="col-md-3 text-center">
                        <span class="glyphicon glyphicon-ok"></span>
                        <span class="fh5co-counter js-counter" data-from="0" data-to="@ViewBag.lessonViewsNo" data-speed="1000" data-refresh-interval="50"></span>
                        <span class="fh5co-counter-label">LESSON COMPLETIONS</span>
                    </div>
                </div>
            </div>
        </div>

@if (ViewBag.currentUser != null)
{
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
               
                    <p style="font-size: 1.2em; font-weight:400; border:2px solid red;padding:5px 0px">You completed @ViewBag.CourseCompletionsNo Courses. 
                     <br /> Requirement: 6 courses per a year.</p>
               
            </div>
        </div>

}

    </div>


<!-- hide: expand the function later
   @*<div id="fh5co-blog" class="blog-flex">
        <div class="featured-blog" style="background-image: url(../../Content/images/blog-1.jpg);">
            <div class="desc-t">
                <div class="desc-tc">
                    <span class="featured-head">Featured Posts</span>
                    <h3><a href="#">Top 20 Best WordPress Themes 2017 Multi Purpose and Creative Websites</a></h3>
                    <span><a href="#" class="read-button">Learn More</a></span>
                </div>
            </div>
        </div>
        <div class="blog-entry fh5co-light-grey">
            <div class="row animate-box">
                <div class="col-md-12">
                    <h2>Latest Posts</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 animate-box">
                    <a href="#" class="blog-post">
                        <span class="img" style="background-image: url(../../Content/images/blog-2.jpg);"></span>
                        <div class="desc">
                            <h3>26 Best Education WordPress Themes 2017 You Need To See</h3>
                            <span class="cat">Collection</span>
                        </div>
                    </a>
                </div>
                <div class="col-md-12 animate-box">
                    <a href="#" class="blog-post">
                        <span class="img" style="background-image: url(../../Content/images/blog-1.jpg);"></span>
                        <div class="desc">
                            <h3>16 Outstanding Photography WordPress Themes You Must See</h3>
                            <span class="cat">Collection</span>
                        </div>
                    </a>
                </div>
                <div class="col-md-12 animate-box">
                    <a href="#" class="blog-post">
                        <span class="img" style="background-image: url(../../Content/images/blog-3.jpg);"></span>
                        <div class="desc">
                            <h3>16 Outstanding Photography WordPress Themes You Must See</h3>
                            <span class="cat">Collection</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>*@ 
-->
</div><!-- END container-wrap -->