Controllers/CourseCompletionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FamilySite.UI.MVC.Controllers
{
    [Authorize]
    public class CourseCompletionsController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: CourseCompletions
        public ActionResult Index(string filter)
        {
            //if a user is "Admin" or "Parent", it can see all course completions of all members.
            //Other users can see only their records.
            if (User.IsInRole("Admin") || User.IsInRole("Parent"))
            {
                var courseCompletions = db.CourseCompletions.Include(c => c.Cours).Include(c => c.UserDetail);
                var members = db.UserDetails.ToList();

                foreach (var x in members)  // select list 
                {
                    if(!string.IsNullOrEmpty(filter))
                    {
                        if(x.UserID == filter)
                        {
                            courseCompletions = db.CourseCompletions.Where(c => c.UserDetail.FirstName == x.FirstName).Include(c => c.Cours).Include(c => c.UserDetail);
                        }
                    }
                }

                ViewBag.filter = new SelectList(db.UserDetails, "UserID", "FirstName");
                return View(courseCompletions.ToList());
            }
            else // a user is not a admin or a parent. can see only their records.
            {
                string currentUserID = User.Identity.GetUserId();
                var courseCompletions = db.CourseCompletions.Include(c => c.Cours).Include(c => c.UserDetail).Where(x => x.UserID == currentUserID);
                return View(courseCompletions.ToList());
            }
            
        }

        // GET: CourseCompletions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string currentUserID = User.Identity.GetUserId();
            CourseCompletion courseCompletion = db.CourseCompletions.Find(id);
            if (courseCompletion == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (User.IsInRole("Parent") || User.IsInRole("Admin") || courseCompletion.UserID == currentUserID)
                {
                    return View(courseCompletion);
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
        }

        [Authorize(Roles ="Admin")]
        // GET: CourseCompletions/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName");
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: CourseCompletions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseCompletionID,UserID,CourseID,DateCompleted")] CourseCompletion courseCompletion)
        {

            if (ModelState.IsValid)
            {

                db.CourseCompletions.Add(courseCompletion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", courseCompletion.CourseID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", courseCompletion.UserID);
            return View(courseCompletion);
        }

        [Authorize(Roles = "Admin")]
        // GET: CourseCompletions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseCompletion courseCompletion = db.CourseCompletions.Find(id);
            if (courseCompletion == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", courseCompletion.CourseID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", courseCompletion.UserID);
            return View(courseCompletion);
        }

        [Authorize(Roles ="Admin")]
        // POST: CourseCompletions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseCompletionID,UserID,CourseID,DateCompleted")] CourseCompletion courseCompletion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseCompletion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", courseCompletion.CourseID);
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", courseCompletion.UserID);
            return View(courseCompletion);
        }

        [Authorize(Roles = "Admin")]
        // GET: CourseCompletions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseCompletion courseCompletion = db.CourseCompletions.Find(id);
            if (courseCompletion == null)
            {
                return HttpNotFound();
            }
            return View(courseCompletion);
        }

        [Authorize(Roles ="Admin")]
        // POST: CourseCompletions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseCompletion courseCompletion = db.CourseCompletions.Find(id);
            db.CourseCompletions.Remove(courseCompletion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CourseCompletions/Create.cshtml
@model FamilySite.DATA.EF.CourseCompletion

@{
    ViewBag.Title = "Add New Course Completion";
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>

   

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div id="CourseDetailsContainer">
                <div class="form-horizontal">
                    <hr />

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserID, "User ID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-9">
                            @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-9">
                            @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DateCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.DateCompleted, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DateCompleted, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>

                    <div id="tdFooter">
                        <p>
                            <input type="submit" value="Create" class="btn btn-primary" />|

                            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                        </p>
                    </div>
                </div>

              
        }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CourseCompletions/Delete.cshtml
@model FamilySite.DATA.EF.CourseCompletion

@{
    ViewBag.Title = "Delete Course Completion of " + Model.UserDetail.FirstName;
}
<div id="family-wrapper">
    <h2>@ViewBag.Title</h2>

    <h3 style="display:inline-block">
        Are you sure you want to delete course completion on
        <span class="myWarning">@Model.DateCompleted.ToShortDateString()</span>?
    </h3>

    <div style="display:inline-block">

        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-primary" />|
                @Html.ActionLink("No", "Index", null, new { @class = "btn btn-danger" })
            </div>
        }
</div>
    </div>

Views/CourseCompletions/Details.cshtml
@model FamilySite.DATA.EF.CourseCompletion

@{
    ViewBag.Title = "Course Completion";
}


<div id="family-wrapper">
    <div>
        <h4>@ViewBag.Title</h4>
        <div id="CourseDetailsContainer">

            <div id="tdHeader">
                <h3>@Html.DisplayFor(model => model.Cours.CourseName)</h3>
            </div>

            <div style="text-align:center">

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.DateCompleted)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DateCompleted)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UserDetail.FirstName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UserDetail.FirstName)
                    </dd>

                </dl>

            </div>
           

            <div>

                <p style="border-bottom: 3px solid dodgerblue;text-align:center"> All Courses Completed in this year</p>

            </div>

            <div id="tdFooter">
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseCompletionID }, new { @class = "btn btn-primary" })@:|
                }
                @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>


Views/CourseCompletions/Edit.cshtml
@model FamilySite.DATA.EF.CourseCompletion

@{
    ViewBag.Title = "Edit Course Completetion on " + Model.DateCompleted.ToShortDateString();
}

<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div id="CourseDetailsContainer">
            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CourseCompletionID)

                <div class="form-group">
                    @Html.LabelFor(model => model.UserID, "User", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-9">
                        @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-9">
                        @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.DateCompleted, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateCompleted, "", new { @class = "text-danger" })
                    </div>
                </div>

                
            </div>
            

            <div class="clearfix"></div>

                <div id="tdFooter">
                    <p>
                        <input type="submit" value="Save" class="btn btn-primary" />|

                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                    </p>
                </div>

        </div>


    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CourseCompletions/Index.cshtml
@model IEnumerable<FamilySite.DATA.EF.CourseCompletion>

@{
    ViewBag.Title = "Course Completion";
}
<div id="family-wrapper">
<h3>@ViewBag.Title</h3>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Add New Course Completion", "Create")
    </p>
}

@if (User.IsInRole("Admin") || User.IsInRole("Parent"))
{
    <div class="buttons">
        @using (Html.BeginForm("Index", "CourseCompletions", FormMethod.Get))
        {
            @Html.DropDownList("filter", null, "Filter by a Member", new { onchange = "this.form.submit();"})
            @Html.ActionLink("Return To Full List", "Index", "CourseCompletions")
        }

    </div>

}


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cours.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserDetail.FirstName)
            </th>
            @if (User.IsInRole("Admin"))
            {
                <th></th>
            }

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.DateCompleted.ToShortDateString(), "Details", new { id = item.CourseCompletionID })
                    @*@Html.DisplayFor(modelItem => item.DateCompleted)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cours.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserDetail.FirstName)
                </td>

                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.CourseCompletionID }) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.CourseCompletionID }) |*@
                        @Html.ActionLink("Delete", "Delete", new { id = item.CourseCompletionID })
                    </td>
                }

            </tr>
        }
    </tbody>
</table>
</div>